apiVersion: v1
kind: Service
metadata:
  name: sdc-svc
  labels:
    app: sdc
spec:
  ports:   
  - nodePort: 31493
    port: 18630
    targetPort: 18630
    protocol: TCP
  selector:
    app: sdc
  type: NodePort
